config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get '/about', to: 'welcome#about'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
 
  get '/auth/facebook/callback' => 'sessions#create'
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :trips, only: [:index]

  resources :users do
    resources :trips, only: [:new, :create, :show, :edit, :update, :destroy, :index]
  end
  
end

app/models/trip.rb
require 'pry'
class Trip < ApplicationRecord
    belongs_to :user
    has_many :eatery_trips                                         
    has_many :eateries, through: :eatery_trips, dependent: :destroy
    validates :title, :presence => true
    validates :description, :presence => true

    accepts_nested_attributes_for :eatery_trips
   
  # def eatery_trips_attributes=(attributes)
  #   attributes.values.each do |attribute|
  #     if attribute[:eatery_id].present? #eatery exists
  #       eatery_trip = EateryTrip.new(attribute)
  #       eatery_trip.trip = self 
  #       eatery_trip.eatery = Eatery.find(attribute[:eatery_id].to_i)
  #       self.eatery_trips << eatery_trip
  #     else
  #       eatery_trip = EateryTrip.new(attribute)
  #       eatery_trip.trip = self 
  #       eatery_trip.save
  #     end

  #   end
  # end
  
  #self.eatery_trips.build(attribute) error moves to update with this line

  def self.create_from_collection(trips) #for scraper
    u = User.find_by(:name => "Admin")
      trips.each do |trip_hash|  
        binding.pry
        trip = u.trips.create(:title => trip_hash[:title], :description => trip_hash[:description])
          trip_hash[:eateries].each do |eatery|
              a = trip.eateries.create(:name => eatery[:name], :city => eatery[:city], :state => eatery[:state], :food_categories => eatery[:food_categories],
                                   :about => eatery[:about], :dishes => eatery[:dishes])
          end      
      end
    end
end

app/controllers/trips_controller.rb
require 'pry'
class TripsController < ApplicationController
    before_action :verify_user, except: [:show, :index]
    before_action :find_user_by_id, except: [:new, :index]
    before_action :find_trip_by_id, only: [:show, :edit, :update]

    def new
      @user = current_user
      @trip = @user.trips.build
      3.times { @trip.eatery_trips.build }
    end
   
    def create
      @trip = @user.trips.build(trip_params)
      if @trip.save
        redirect_to user_trip_path(@user, @trip)
      else
        render :new 
      end
    end
  
    def show
    end

    def index
      if params[:user_id]
        @trips = User.find(params[:user_id]).trips
      else
        @trips = Trip.all
      end
    end

    def edit
    end

    def update
      if @trip.update(trip_params)
        redirect_to user_trip_path(current_user, @trip)
      else
        render :edit
      end
    end

    def destroy
      @trip = @user.trips.find(params[:id])
      @trip.destroy
      redirect_to user_trips_path(@user)
    end
    
    private 

    def trip_params 
        params.require(:trip).permit(:id, :title, :description, :eatery_trips_attributes => [:id, :visit_date, :review, :eatery_id, :eatery_attributes => [:id, :city, :state, :name, :about, :food_categories, :dishes]])
    end

    def find_trip_by_id
      @trip = Trip.find(params[:id])
    end

    def find_user_by_id
      @user = User.find(params[:user_id])
    end
    
end

app/helpers/trips_helper.rb
require 'pry'
module TripsHelper

end

app/views/trips/_eatery_attributes.html.erb
<%= fff.label :city %>
<%= fff.text_field :city, placeholder: "Ex: Savannah" %><br /><br />
<%= fff.label :state %>
<%= fff.text_field :state, placeholder: "Ex: GA" %><br /><br />
<%= fff.label :name %>
<%= fff.text_field :name, placeholder: "Cotton & Rye" %><br /><br />
<%= fff.label :about %>
<%= fff.text_field :about, placeholder: "Pro tip: Book a private dinner inside the original bank vault.", size: "50%" %><br /><br />
<%= fff.label :food_categories %>
<%= fff.text_field :food_categories, placeholder: "Southern food, dinner, dessert", size: "50%" %><br /><br />
<%= fff.label :dishes %>
<%= fff.text_field :dishes, placeholder: "Crispy chicken wings, peanut butter pie", size: "50%" %><br /><br />

app/views/trips/_eatery_fields.html.erb
<ul>
  <%= fff.label :city %>
  <%= fff.text_field :city, placeholder: "Ex: Savannah" %><br /><br />
  <%= fff.label :state %>
  <%= fff.text_field :state, placeholder: "Ex: GA" %><br /><br />
  <%= fff.label :name %>
  <%= fff.text_field :name, placeholder: "Cotton & Rye" %><br /><br />
  <%= fff.label :about %>
  <%= fff.text_field :about, placeholder: "Pro tip: Book a private dinner inside the original bank vault.", size: "50%" %><br /><br />
  <%= fff.label :food_categories %>
  <%= fff.text_field :food_categories, placeholder: "Southern food, dinner, dessert", size: "50%" %><br /><br />
  <%= fff.label :dishes %>
  <%= fff.text_field :dishes, placeholder: "Crispy chicken wings, peanut butter pie", size: "50%" %><br /><br />
</ul>

app/views/trips/_eatery_trips_fields.html.erb
<%= ff.label :visit_date %>
<%= ff.date_field :visit_date %><br /><br />
<%= ff.label :review %>
<%= ff.text_area :review, placeholder: "Add notes here." %><br /><br />

app/views/trips/_form.html.erb
<% require 'pry' %>
<%= form_for [@user, @trip] do |f| %>
    <% if @trip.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this post from being saved:</h2>
          <% @trip.errors.full_messages.each do |message| %>
           <ul>
           <li><%= message %></li>
           </ul>
          <% end %>
      </div>
    <% end %>
     
    <div>
      <%= render "trip_fields", f: f %>
    </div>
   
    <div id="eatery_trips">
      
      <h3>Eatery</h3>
      <%= f.fields_for :eatery_trips do |ff| %>
        <%= ff.collection_select :eatery_id, Eatery.all, :id, :name, {:prompt => 'Select'} %>
      <%= render "eatery_trips_fields", ff: ff %>
      <% end %>
      
    </div>
 
<%= render "submit_button" %>
<% end %> 
 

app/views/trips/_submit_button.html.erb
<br / >
<br / >
    <%= submit_tag action_name == 'new' ? 'Create Itinerary' : 'Save Changes to Itinerary' %>

app/views/trips/_trip_attributes.html.erb
<%= f.label :title %>
<%= f.text_area :title, placeholder: "Ex: Brunch and Breweries" %> <br /><br />
<%= f.label :description %>
<%= f.text_area :description, placeholder: "Ex: Southern Road Trip 2021" %><br /><br />

app/views/trips/_trip_fields.html.erb
<%= f.label :title %>
<%= f.text_area :title, placeholder: "Ex: Brunch and Breweries" %> <br /><br />
<%= f.label :description %>
<%= f.text_area :description, placeholder: "Ex: Southern Road Trip 2021" %><br /><br />

app/views/trips/edit.html.erb
<h1>Edit Trip</h1>

<%= render partial: "form", locals: { trip: @trip } %>

<br/>
<br/>
<% if user_match? %> 
    <%= link_to "Back to My Road Trip Itineraries", user_trips_path(@user)%><br><br>
    <%= link_to "Delete Itinerary", user_trip_path(@user, @trip), method: "delete" %> <br><br>
<% end %>

app/views/trips/index.html.erb
<% require 'pry' %>
<h1>Trip Itineraries</h1>

<% @trips.each do |trip| %>
  <p><%= link_to trip.title, user_trip_path(trip.user_id, trip) %></p> 
<% end %>

<br />
<br />

<%= link_to "CREATE NEW ROAD TRIP ITINERARY", new_user_trip_path(current_user) if current_user %>

<br />
<br />

app/views/trips/new.html.erb
<h1>Hello there. Create a meal-driven road trip itinerary below.</h1>

<br><br>

<body style="font-size: 16px;">

<%= render partial: "form", locals: { trip: @trip } %>

</body>

app/views/trips/show.html.erb
<% require 'pry' %>

<body>

<h1>Road Trip Itinerary: <%= @trip.title %></h1>

<h2>Description: <%= @trip.description %></h2>

  <% @trip.eatery_trips.each do |eatery_trip| %>
    <h2>Restaurant name: <%= eatery_trip.eatery.name %></h2>
    <p>Location: <%= eatery_trip.eatery.location if eatery_trip.eatery.location != "" %>
    <p>Food categories: <%= eatery_trip.eatery.food_categories %>
    <p>Hot tips: <%= eatery_trip.eatery.about %>
    <p>Dishes: <%= eatery_trip.eatery.dishes %> 
    <% if eatery_trip.visit_date_exists %>
       <p>Date visited: <%= eatery_trip.format_date %></p>
  
    <% end %>
    <% if eatery_trip.review_exists %>
      <p>Review: <%= eatery_trip.review %></p>
    <% end %>
  <% end %>
  
</body>
<br/>
<br/>
<% if user_match? %> 

    <%= link_to "Back to My Road Trip Itineraries", user_trips_path(@user)%><br><br>
    <%= link_to "Edit Food Road Trip Itinerary", edit_user_trip_path(@user, @trip) %><br><br>
    <%= link_to "Delete Food Road Trip Itinerary", user_trip_path(@user, @trip), method: "delete" %> <br><br>
   
<% end %>