config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get '/about', to: 'welcome#about'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
 
  get '/auth/facebook/callback' => 'sessions#create'
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :trips, only: [:index]

  resources :users do
    resources :trips, only: [:new, :create, :show, :edit, :update, :destroy, :index]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trips, dependent: :destroy

  validates :name, :presence => true
  validates :email, :presence => true
  validates :email, :uniqueness => true
  validates :email, email: true
  
  has_secure_password

  def self.login_from_omniauth(auth)
    find_from_omniauth(auth) || create_from_omniauth(auth)
  end

  def self.find_from_omniauth(auth)
    find_by(:uid => auth[:uid])
  end

  def self.create_from_omniauth(auth)
    create(:uid => auth['uid'], 
           :name => auth['info']['name'],
           :email => auth['info']['email'],
           :image => auth['info']['image'], 
           :password => SecureRandom.hex(10))
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_user, only: [:show]

  def new
    @user = User.new
  end 

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      login(@user)
      redirect_to root_path
      flash[:notice] = "Account successfully created."     
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @trips = @user.trips
  end

  private 

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/views/users/new.html.erb
<% require 'pry' %>
<header>
  <h1>Account Signup</h1>

  <%= form_for @user, url: signup_path do |f| %>

  <% if @user.errors.any? %>
  Please address the following before submitting:
   <% @user.errors.full_messages.each do |message| %>
     <h3><i><%= message %></i></h3>
  <% end %>
<% end %>
   
      <%= f.label :name %>
      <%= f.text_field :name %><br />
      <%= f.label :email %>
      <%= f.text_field :email %><br />

      <%= f.label :password %>
      <%= f.password_field :password %><br />
      <br />
      <%= f.submit "Create account" %>
    <% end %>
</header >
<br/>
<br/>

<footer id="footer">

  <%= link_to('Sign in with Facebook', '/auth/facebook', method: :post) %>

</footer>

<br>
<br>

app/views/users/show.html.erb
<% require 'pry' %>
<h1>Hello, <%= @user.name %>.</h1>

<h2>Here's where you've eaten: </h2>

<% @trips.each do |trip| %>
    <% trip.eatery_trips.visited.to_a.each do |eatery| %>
      <% id = eatery.eatery_id %>
      <% e = Eatery.find_by(id: id) %>
      <ul>
        <li><%= e.name %></li>
        <% if eatery.review.present? %>
          <p>Your review: <%= eatery.review %></p>
        <% end %>
      </ul>
    <% end %>
<% end %>

<%= link_to "Back to My Road Trip Itineraries", user_trips_path(@user) %> 