config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get '/about', to: 'welcome#about'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
 
  get '/auth/facebook/callback' => 'sessions#create'
  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :trips, only: [:index]

  resources :users do
    resources :trips, only: [:new, :create, :show, :edit, :update, :destroy, :index]
  end
  
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>  

app/views/layouts/_footer.html.erb
<br />
<br />
<center><strong><footer style="font-size:100%;">
<% if current_user %>
Currently logged in as <%= current_user.name %>.
<% end %>
</footer></strong</center>
</html>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li><%=link_to "HOME", root_path %></li>
            <li><%=link_to "ABOUT", about_path %></li>
            <li><%=link_to "ITINERARIES", trips_path %></li>
        
            <% if current_user %>
              <li><%=link_to "PROFILE", user_path(current_user) %></li>
              <li><%=link_to "LOG OUT", logout_path %></li>
            <% else %>
              <li><%=link_to "SIGN UP", signup_path %></li>
              <li><%=link_to "LOG IN", login_path %></li>
            <% end %>

        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ultimate Food Road Trip Planner</title>
      <link rel="preconnect" href="https://fonts.gstatic.com">
      <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
        <style>
          body {
          font-family: 'Roboto', serif;
          font-size: 16px;
          }
        </style>
          <meta name="viewport" content="width=device-width,initial-scale=1">
          <%= csrf_meta_tags %>
          <%= csp_meta_tag %>
          <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
          <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

        <%= render "layouts/navbar" %>
  </head>

  <body>
    <div class="wrapper">
      <h1 class="site-header__logo">
        <center><%= image_tag ("spoonfork.jpg") %></center>
      </h1>
    </div>

    <center><%= image_tag ("nathan-dumlao-nCeR4kAcZ2c-unsplash.jpg"), size: "500x750" %></center>

    <div class='content'>

    <%= render "layouts/flash" %>

      <%= yield %>
    </div>

  </body>
  <%= render "layouts/footer" %>
</html>